### ISSUE TITLE
Support for username/password

### ISSUE THREAD

**Issue by BjornAtle** [anthonyeden/Livewire-Simple-Delegation-Switcher#7]
I hope you can add support for devices which is protected with username/password. Thanks!

**Comment by anthonyeden** [comment]
Hello,
This has been supported for quite some time. Simply set the field "DevicePassword" in the config file.

You only need to specify the password - no username is necessary.

Thanks,
Anthony.

**Comment by BjornAtle** [comment]
Wow. Thanks! I didn't actually try that. Sorry!
I'm blushing :-)
And thanks for a very useful program, I use it to monitor our playouts on my desktop.
I also noticed the command line version, which is definitely interesting for us.
I'm also wondering if you will support vmix?
I understand that the command line version does support that, but does it have a panel?



Sendt fra min iPhone

15. mar. 2019 kl. 02:00 skrev Anthony Eden <notifications@github.com<mailto:notifications@github.com>>:


Hello,
This has been supported for quite some time. Simply set the field "DevicePassword" in the config file.

You only need to specify the password - no username is necessary.

Thanks,
Anthony.

-

**Comment by anthonyeden** [comment]
Hi Bjørn,
Not a problem. The Command Line version supports vMixes (on Engines, not QORs). However, the CLI doesn't have a GUI. It's more designed for using via automation systems, batch files, scheduled tasks, etc. I'm currently looking for ways to add a rules engine, GUIs, etc.
